### ISSUE TITLE
running WINE with capabilities

### ISSUE THREAD

**Issue by smitsohu** [Whonix/security-misc#67]
https://github.com/Whonix/security-misc/blob/71ae6239168d829e25670ffa856ee0f011a168a9/etc/sysctl.d/30_security-misc.conf#L52-L58

I think you need to be careful that ptrace use is tightly restricted by other means (e.g. AppArmor), as otherwise the suggested setup is always one vulnerability short of giving wineserver and wine-preloader unrestricted root powers.
A related question is if WINE was written with capabilities in mind at all.

**Comment by madaidan** [comment]
We already use apparmor to restrict ptrace. Individual apparmor profiles for apps restrict it.

https://github.com/Whonix?q=apparmor-profile-&type=&language=

The full system apparmor policy also restricts it a bit.

https://github.com/Whonix/apparmor-profile-everything/blob/master/etc/apparmor.d/abstractions/init-systemd#L37

More fine-grained restrictions are planned.

We don't add those capabilities to WINE by default anyway. It's the user's choice.

**Comment by adrelanos** [comment]
Please comment / re-open if you think this isn't solved.
